# Path to your oh-my-zsh installation.
  export ZSH=/home/norato/.oh-my-zsh

ZSH_THEME="amuse"

plugins=(git)


source $ZSH/oh-my-zsh.sh


# Example aliases
# alias zshconfig='atom ~/.zshrc'
# alias ohmyzsh="mate ~/.oh-my-zsh"


alias gdmb='git branch --merged master | grep -v master | xargs git branch -d'

alias gadd='git add -p'

alias gpu='git push --set-upstream origin $(git rev-parse --abbrev-ref HEAD)'
alias gpsm='git push heroku-staging master'

alias go='git open'

alias elastic='/home/norato/Projects/elasticsearch-2.3.3/bin/elasticsearch'

export PATH="$PATH:$HOME/.rvm/bin" # Add RVM to PATH for scripting
